version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - RECALL_API_KEY=${RECALL_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - CARTESIA_API_KEY=${CARTESIA_API_KEY}
    volumes:
      - ./backend:/app
    restart: unless-stopped
